services:
  alexa-reviews:
    image: bsha2nk/alexa-reviews:latest
    ports:
      - 8080:8080
    networks:
      - alexa-reviews-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/alexa-reviews
      - status-check-interval=30000
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:9.0.1
    ports:
      - 3306:3306
    networks:
      - alexa-reviews-net
    volumes:
      - alexa-reviews-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 10s
      timeout: 100s
    environment:
      - MYSQL_DATABASE=alexa-reviews
      - MYSQL_USER=reviews
      - MYSQL_PASSWORD=reviews
      - MYSQL_ROOT_PASSWORD=root

networks:
  alexa-reviews-net:

volumes:
  alexa-reviews-volume: